#!/usr/bin/env bash
# example: ctmux -m 4 -c /bin/ssh io{3,s1}host{1..30}

is_subshell() {
    if [ "${0##*/}" = ctmux ]
    then
        return 0
    fi

    return -1
}

error() {
    echo "$@" >&2
    exit 1
}

cluster_tmux() {
    local session_name="ctmux-$(date -uIdate)"
    local -i modulus=4
    local ssh_command="$HOME/bin/j"

    while getopts ":s:m:c:" opt
    do
        case $opt in
            s)
                session_name="$OPTARG"
                ;;
            m)
                modulus="$OPTARG"
                ;;
            c)
                ssh_command="$OPTARG"
                ;;
            \?)
                error "I don't know what you mean: -$OPTARG"
                ;;
        esac
    done

    shift $(( OPTIND-1 ))

    local remote_hosts=("$@")

    tmux new-session -d -s "$session_name"

    local count=0
    for remote_host in "${remote_hosts[@]}"
    do
        local window_command="${ssh_command} '${remote_host}'"
        if ((  count % modulus == 0 ))
        then
            tmux new-window -t "${session_name}" "${window_command}"
        else
            tmux split-window -v -t "${session_name}" "${window_command}"
            tmux select-layout -t "${session_name}" even-vertical
        fi

        let count+=1
    done
}

is_subshell "$0" && cluster_tmux "$@"
